apiVersion: apps/v1
kind: Deployment
metadata:
  name: jeensns
  labels:
    app: jeensns
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jeensns
      tier: backend
  template:
    metadata:
      labels:
        app: jeensns
        tier: backend
    spec:
      containers:
      - name: jeensns
        image: app/jeensns
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: jeensns
  labels:
    app: jeensns
    tier: backend
spec:
  selector:
    app: jeensns
    tier: backend
  ports:
  - port: 8080
    name: k8s-backend

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jeensns
spec:
  rules:
  - host: jeensnsk8s.bff.cn
    http:
      paths:
      - backend:
          serviceName: jeensns
          servicePort: k8s-backend






 