apiVersion: apps/v1
kind: Deployment
metadata:
  name: jeesns
  labels:
    app: jeesns
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jeesns
      tier: backend
  template:
    metadata:
      labels:
        app: jeesns
        tier: backend
    spec:
      containers:
      - name: jeesns
        image: app/jeesns
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: jeesns
  labels:
    app: jeesns
    tier: backend
spec:
  selector:
    app: jeesns
    tier: backend
  ports:
  - port: 8080
    name: k8s-backend

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jeesns
spec:
  rules:
  - host: jeesnsk8s.bff.cn
    http:
      paths:
      - backend:
          serviceName: jeesns
          servicePort: k8s-backend






 